Repository open-company/open-company-bot, pull requests merged in 2019-01, with the labels that each got.

#50 Make sure the correct keys are used to generate the id-token.
  src/oc/bot/async/bot.clj
Labels: ready for deploy

#53 Kinesis s3 sns
  project.clj
  src/oc/bot/async/bot.clj
Labels: ready for deploy

#55 Digest design
  src/oc/assets/img/carrot_logo.png
  src/oc/assets/img/slack-digest-background.png
  src/oc/bot/config.clj
  src/oc/bot/digest.clj
  src/oc/bot/image.clj
Labels: awaiting revision

#56 Eastwood config
  project.clj
  src/oc/bot/async/bot.clj
  src/oc/bot/async/slack_action.clj
  src/oc/bot/config.clj
Labels: ready for deploy

#58 4x banner
  src/oc/assets/img/slack-digest-background.png
  src/oc/bot/image.clj
Labels: reviewing

#57 Reminders
  src/oc/bot/async/bot.clj
  src/oc/bot/config.clj
Labels: ready for deploy

#59 Final reminders tweaks
  src/oc/bot/async/bot.clj
Labels: ready for deploy

#61 Digest feedback
  src/oc/bot/digest.clj
Labels: reviewing
